
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConvexClientProviders from "../../providers/ConvexClientProviders";
import ConvexAuthGate from "@/components/ConvexAuthGate";
import LoadingLogo from "@/components/shared/LoadingLogo";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/ui/themes/theme-provider";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "rtca",
  description: "Generated by aman kumar choudhary",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" suppressHydrationWarning className="light" style={{ colorScheme: "light" }}>

      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
          <ConvexClientProviders>
            <ConvexAuthGate>
              <TooltipProvider>
                {children}
              </TooltipProvider>
              <Toaster richColors />
            </ConvexAuthGate>
          </ConvexClientProviders>
        </ThemeProvider >
      </body>
    </html>

  );
}
